// actions.js
export const Action = Object.freeze({
    GET: 'get',
    LIST: 'list',
    ADD: 'add',
    UPDATE: 'update',
    SOFT_DELETE: 'softdelete',
    HARD_DELETE: 'harddelete',
    RESTORE: 'restore',
    ACTIVE: 'active',
    PASSIVE: 'passive',
    ARCHIVE: 'archive',
    UNARCHIVE: 'unarchive',
    REPORT: 'report',
    STATISTIC: 'statistic',
    PRINT: 'print',
    IMPORT: 'import',
    EXPORT: 'export',
    APPROVE: 'approve',
    REJECT: 'reject',
    PUBLISH: 'publish',
    DRAFT: 'draft',
    CLONE: 'clone',
    SHARE: 'share',
    TRANSFER: 'transfer',
    MAIL: 'mail',
    AUDIT: 'audit',
    MONITOR: 'monitor',
    VALIDATE: 'validate',
    SYNC: 'sync',
    SCHEDULE: 'schedule',
  });
  